In [3]:
import numpy as np 
v= np.random.randint(1,4,size=(2,2))
s=v.tolist()
print (s)

[[3, 1], [1, 2]]


In [4]:
v = np.random.randint(1,4,size=(2,2))
np.trace(v)

3

In [5]:
import numpy as np
v = np.random.randint(1,4,size=(2,2))
x = int(input())
result = []
for i in v:
  for j in i:
    if j>x:
      result.append(j)
print (v)
print ("---")
print (result)


1
[[3 2]
 [1 2]]
---
[3, 2, 2]


In [8]:
arr1 = np.random.randint(1,9,size=(3,3))
arr2 = np.random.randint(1,9,size=(3,3))
arr3 = np.zeros((3,3))
arr_sh= arr1.shape
for i in range(arr_sh[0]):
  for j in range(arr_sh[1]):
    arr3[i,j]=arr1[i,j]+arr2[i,j]
print(arr1)
print("_ _ _ _ _ _")
print("_ _ _ _ _ _")
print(arr2)
print("_ _ _ _ _ _")
print("_ _ _ _ _ _")
print(arr3)

[[5 5 3]
 [7 8 3]
 [5 3 7]]
_ _ _ _ _ _
_ _ _ _ _ _
[[8 5 3]
 [2 1 5]
 [6 5 3]]
_ _ _ _ _ _
_ _ _ _ _ _
[[13. 10.  6.]
 [ 9.  9.  8.]
 [11.  8. 10.]]


In [12]:
import numpy as np
my_arr= np.random.randint(1,9,size=(3,3))
row_mean=np.mean(my_arr, axis=0)
arr_sh= my_arr.shape
new_arr=np.zeros((3,3))
for i in range(arr_sh[0]):
  for j in range(arr_sh[1]):
    new_arr[i,j]= my_arr[i,j]-row_mean[i]
    
print (my_arr)
print("_ _ _ _ _ _")
print("_ _ _ _ _ _")
print("")
print (new_arr)





[[5 6 6]
 [2 5 2]
 [3 3 7]]
_ _ _ _ _ _
_ _ _ _ _ _

[[ 1.66666667  2.66666667  2.66666667]
 [-2.66666667  0.33333333 -2.66666667]
 [-2.         -2.          2.        ]]
